2023-01-01 15:32:11,119 INFO    MainThread:23418 [wandb_setup.py:_flush():68] Configure stats pid to 23418
2023-01-01 15:32:11,119 INFO    MainThread:23418 [wandb_setup.py:_flush():68] Loading settings from /scratch/gua/.config/wandb/settings
2023-01-01 15:32:11,119 INFO    MainThread:23418 [wandb_setup.py:_flush():68] Loading settings from /scratch/gua/Documents2/Sym-NCO/Sym-NCO-AM/wandb/settings
2023-01-01 15:32:11,119 INFO    MainThread:23418 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-01 15:32:11,119 INFO    MainThread:23418 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'Sym-NCO-AM/run.py', 'program': '/scratch/gua/Documents2/Sym-NCO/Sym-NCO-AM/run.py'}
2023-01-01 15:32:11,119 INFO    MainThread:23418 [wandb_init.py:_log_setup():476] Logging user logs to /scratch/gua/Documents2/Sym-NCO/Sym-NCO-AM/wandb/run-20230101_153211-3hs5uzym/logs/debug.log
2023-01-01 15:32:11,120 INFO    MainThread:23418 [wandb_init.py:_log_setup():477] Logging internal logs to /scratch/gua/Documents2/Sym-NCO/Sym-NCO-AM/wandb/run-20230101_153211-3hs5uzym/logs/debug-internal.log
2023-01-01 15:32:11,120 INFO    MainThread:23418 [wandb_init.py:init():516] calling init triggers
2023-01-01 15:32:11,120 INFO    MainThread:23418 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-01-01 15:32:11,120 INFO    MainThread:23418 [wandb_init.py:init():569] starting backend
2023-01-01 15:32:11,120 INFO    MainThread:23418 [wandb_init.py:init():573] setting up manager
2023-01-01 15:32:11,126 INFO    MainThread:23418 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-01-01 15:32:11,128 INFO    MainThread:23418 [wandb_init.py:init():580] backend started and connected
2023-01-01 15:32:11,131 INFO    MainThread:23418 [wandb_init.py:init():658] updated telemetry
2023-01-01 15:32:11,135 INFO    MainThread:23418 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2023-01-01 15:32:14,173 WARNING MsgRouterThr:23418 [router.py:message_loop():77] message_loop has been closed
2023-01-01 15:32:21,146 ERROR   MainThread:23418 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/scratch/gua/anaconda3/envs/rl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/scratch/gua/anaconda3/envs/rl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/scratch/gua/anaconda3/envs/rl/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
